### ISSUE TITLE
Great job! I am a noob. Do you get any idea to train fetchpickandplace-v1 using the same algorithm?  

### ISSUE THREAD

**Issue by Chao-Hou** [pipatth/robot-rl-cscie89#1]
Great job! I am a noob. Do you get any idea to train fetchpickandplace-v1 using the same algorithm?  some thing i really need to pay attention , and the difference between the two tasks. I tried to train it on the basis of your code. but didn't make it. Thanks in advance!

**Comment by pipatth** [comment]
Hi. I've never tried fetchpickandplace-v1. Pick and place seems to have more observation spaces and action spaces. You might have to tweak the code. If the code is working but it doesn't converge, I would say that you might want to try different neural net architectures (e.g. more layers, convolutional, etc.). Let me know if you have further questions. Good luck!

**Comment by Chao-Hou** [comment]
I tried several time, but still couldn't make it . Would you like to try fetchpickandplace-v1 with the same algorithm? Considering you have done fetchreach so perfect, it cannot be difficult for you.

**Comment by pipatth** [comment]
Hi Chao-Hou. I don't have a plan to do fetchpickandplace-v1 at this point. But I'll be glad to help anyone. Thanks.

**Comment by GbengaOdesanmi** [comment]
Hi pipatth, Thanks for your awesome presentation, I would be glad if you can help me because am finding it difficult to understand some basic implementation process.
Thanks in anticipation my email(gbenga28@gmail.com)

**Comment by chaiban** [comment]
Hi @pipatth , did you manage to implement for PickAndPlace ?, if so can you share the code ? Thank you! mail: bandi.chai414@gmail.com

**Comment by pipatth** [comment]
@chaiban I haven't try PickAndPlace. It shouldn't be much different than Fetch. You need to give the learner some rewards along the way (hindsight experience replay). Otherwise, the learning is so slow.

**Comment by chaiban** [comment]
Yes, Thank you. I was able to achieve results. 

Do you have any experience on custom environment creation ? 

I created an Environment in mujoco_py for grasping but I am not really sure on how to define action space and observation space. 

is there a possibility that you could help me with that ?

Below image is my environment with gripper and object. I am trying to grasp it using reinforcement learning. Any kind of insight is helpful.  Thank you
![Screenshot from 2019-07-12 14-16-12](https://user-images.githubusercontent.com/38505021/61127553-e0d81380-a4af-11e9-962d-6394190ce598.png)

**Comment by pipatth** [comment]
@chaiban I haven't tried customer environment on Mujoco before. Have you tried looking at https://github.com/openai/gym/tree/master/gym/envs/mujoco ?

**Comment by chaiban** [comment]
@pipatth  Yes, I saw the environments given by mujoco but I am confused on how to actually code. 

Anyways, Thank you. I will work with what I know.
