### ISSUE TITLE
Newbie 

### ISSUE THREAD

**Issue by SohShiHui-UTAR** [pipatth/robot-rl-cscie89#2]
Hi first of all thanks for replying. I am very new and fresh to this project...Would you mind to show the on how to visualize the fetchreach.py inside mujoco and result? Thanks a lot! >,<

**Comment by pipatth** [comment]
Sure. I'll be glad to help. Firstly, did you manage to install Mujoco and mujoco-py
on your computer? They are the hardest part in my opinion.

**Comment by SohShiHui-UTAR** [comment]
Hi sorry for the late reply. I think I have installed successfully as I can visualize my other model in Jupyter notebook. However, I unable to visualize model by using visual studio code as the error is GLEW initialization error: Missing GL version. I have added this:  LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libGLEW.so:/usr/lib/nvidia-384/libGL.so python fetchreach.py but I have no idea how to solve this...

**Comment by pipatth** [comment]
hmm. You might have a different Nvidia driver version (not nvidia-384). Can you find out what nvidia you have in your `/usr/lib`? You might have to adjust your `LD_PRELOAD...` script accordingly.

**Comment by SohShiHui-UTAR** [comment]
Hi, I have reinstalled mujoco-py into windows 10 inside my another laptop...and this takes me for a long time to install,,, so many problems. I get stuck with this error, I don't know do you have this problem or bug before? 
![image](https://user-images.githubusercontent.com/54083801/78539410-1cc4bd00-7825-11ea-90f2-645fa20ab2af.png)

**Comment by pipatth** [comment]
@SohShiHui-UTAR I think you're having the same problem (i.e. cannot load `fetchreach` due to numpy int) as this thread in mujoco-py: https://github.com/openai/mujoco-py/issues/324

Unfortunately, the mujoco-py branch on OpenAI doesn't support Windows. I would suggest you tried out mujoco-py from this unmerged PR: https://github.com/openai/mujoco-py/pull/347

I'll try re-installing and update the instruction for Ubuntu in the next few days. I'll keep you posted if I find anything useful.

**Comment by SohShiHui-UTAR** [comment]
I see, thanks a lot.

**Comment by pipatth** [comment]
Ok. I re-wrote the installation steps. I tried this from a new Ubuntu 19.10 installation and it is working. Please see the README.md

**Comment by SohShiHui-UTAR** [comment]
Thanks!! I will give a try! :)

**Comment by SohShiHui-UTAR** [comment]
Hi, were you using tensorflow version 1.x when you were doing this project?
